### ISSUE TITLE
Make a v1.9.1 release

### ISSUE THREAD

**Issue by dagwieers** [proxytunnel/proxytunnel#1]
Since the release of proxytunnel v1.9.0 there have been many changes, a new v1.9.1 release would bring these to users. The current CHANGES file hints for a v1.9.1 release including:
- Switch to HTTP/1.1 commands, so we can tunnel over JoikuSpot's which
  don't understand http/1.0 command (Mark Janssen)
- NTLMv2 fixes by Giulio Galante giulio.galante@fastwebnet.it
- Read http_proxy before HTTP_PROXY env var

But a log of the changes reveals a few more.

**Comment by Lamieur** [comment]
Is there any post-2008 Windows version of proxytunnel available anywhere?

2 months ago my proxytunnel stopped working because I've updated openssl on my server. Nowadays my httpd doesn't talk SSLv3 even thought I've explicitly had it enabled for years (spoiler: openssl update disables it forcibly, ignoring any custom configs), ONLY because proxytunnel didn't have a release in 8 years and doesn't talk TLS (no to mention TLSv1.2).

You're not really a "maintainer" of a piece of software if your users can't use it for years (normal users) or months (me and my mod_ssl configs enabling SSLv3 for the last 2 years). You either produce working versions, or you're not doing anything.

Please?

**Comment by dagwieers** [comment]
None of the maintainers have Windows systems to build proxytunnel on. Luckily this is Open Source and you can build it yourself. Do let us know if you have any problems building proxytunnel on Windows.

**Comment by Lamieur** [comment]
Please provide instructions for building it on Windows then?

Not that I've ever had a computer able to build Windows software myself. The only experience I have with Windows is exactly where I need proxytunnel - and where I lack privileges to install any software, obviously.

But I can get a friend who has a Windows laptop build this for me, if you provide a clear build instructions. And believe me, the only friends I have who do have Windows aren't "technical", so they will come back to me if your cookbook doesn't work :/

**Comment by dagwieers** [comment]
I created a new pull request for this: #15 as the discussion does not belong here.

**Comment by Lamieur** [comment]
True, that's the actual request I was making, regardless of "release" or not. Awesome of you to push this forward, thanks!

**Comment by dagwieers** [comment]
@Lamieur If you look at the other request you can see someone reporting success in building it themselves. It's a matter of installing cygwin and openssl, make and gcc. And then running `make proxytunnel`. You can ask him to send you the executable he build, or try and build it yourself. Good luck !

**Comment by sigio** [comment]
Closing this, no longer relevant
